create new page component
Enterprise-CMCS/macpro-mdct-mfp pull request #112
Opened 2023-09-21 17:14 UTC by cassandradanger

### Description

### Related ticket(s)

MDCT-2813

---
### How to test

### Important updates

---
### Author checklist

- [ ] I have performed a self-review of my code
- [ ] I have added [thorough](https://bit.ly/3zPrxuZ) tests, if necessary
- [ ] I have updated relevant documentation, if necessary
---

_convert to a different template: [test → val](?expand=1&template=test-to-val-deployment.md)_ | _[val → prod](?expand=1&template=val-to-prod-deployment.md)_

2023-10-04 18:35 UTC, keeysnc requested changes
I'm seeing an issue with the repeatable fields on Eval Plan & Funding Sources. Besides that I think everything looks good!
Sidenote: Im not sure but I think that empty funding source card may just be on my end.
<img width="1480" alt="Screenshot 2023-10-04 at 2 27 23 PM" src="https://github.com/Enterprise-CMCS/macpro-mdct-mfp/assets/14514294/05fee978-a8f8-45f6-aa08-6bc0610fe043">

2023-10-04 19:45 UTC, ajaitasaini approved these changes
i can see the dashboard and navigate to/from the 4 pages!

2023-10-04 20:19 UTC, karla-vm commented
> I'm seeing an issue with the repeatable fields on Eval Plan & Funding Sources. Besides that I think everything looks good! Sidenote: Im not sure but I think that empty funding source card may just be on my end. <img alt="Screenshot 2023-10-04 at 2 27 23 PM" width="1480" src="https://user-images.githubusercontent.com/14514294/272675618-05fee978-a8f8-45f6-aa08-6bc0610fe043.png">

I think there's some styling to be done still because this changes how we fill the `EntityCard` component quite a bit, so I'll prioritize that!

2023-10-05 19:34 UTC, keeysnc submitted a review, later dismissed
Looks good!

2023-10-06 03:01 UTC, cassandradanger reviewed
hello!! The quarters and funding source cards are looking good with the updates! 
One thing I noticed is that when I saved items for parts II. and III. for one initiative, they show up for a separate initiative.
Not sure if that's an issue for this PR?

2023-10-06 12:16 UTC, karla-vm commented
> hello!! The quarters and funding source cards are looking good with the updates! One thing I noticed is that when I saved items for parts II. and III. for one initiative, they show up for a separate initiative. Not sure if that's an issue for this PR?

ooh, let me check that out.

2023-10-06 15:40 UTC, ajaitasaini approved these changes
no longer seeing the issue Casie pointed out, for the scope of this ticket everything is working as intended!! great job :D

2023-10-06 17:06 UTC, cassandradanger reviewed
Looks like I can't approve because I opened this PR - but I've reviewed and approve!

2023-10-06 17:43 UTC, ntsummers1 approved these changes

2023-10-06 17:43 UTC, ntsummers1 commented on services/ui-src/src/components/overlays/EntityDetailsDashboardOverlay.tsx
> +                openDrawer={() => openEntityStepOverlay(entity)}
What is this line doing?

2023-10-06 17:43 UTC, ntsummers1 commented on services/ui-src/src/components/reports/ModalOverlayReportPage.tsx
> +
Whats happening here? Can we move this to a function? And should the filter be returning false instead of just return at the very end?

2023-10-06 17:57 UTC, merged