display quarters in quantitative progress
Enterprise-CMCS/macpro-mdct-mfp pull request #437
Opened 2024-02-08 18:15 UTC by cassandradanger

### Description

display the 2 first quarters in the reporting period for Quantitative Objective Progress in the SAR

<img width="690" alt="Screenshot 2024-02-08 at 12 10 15 PM" src="https://github.com/Enterprise-CMCS/macpro-mdct-mfp/assets/10237149/732ff218-b31e-48fb-bc4d-f2b1408fb8ad">

### Related ticket(s)

CMDCT-3233

---
### How to test

- create a WP with an objective that contains quantitative info
- create a SAR off of that WP, go to State Initiatives -> Objectives progress and you should see the 1st two quarters displaying in the quantitative objective progress card

### Important updates

---
### Author checklist

- [ ] I have performed a self-review of my code
- [ ] I have added [thorough](https://shorturl.at/aejkF) tests, if necessary
- [ ] I have updated relevant documentation, if necessary
---

_convert to a different template: [test → val](?expand=1&template=test-to-val-deployment.md)_ | _[val → prod](?expand=1&template=val-to-prod-deployment.md)_

2024-02-09 15:04 UTC, gmrabian approved these changes
Looks good! I don't see how it's limited to just two, but it works!

2024-02-09 18:40 UTC, cassandradanger commented
> Looks good! I don't see how the code limits it to just two 🤔 but it does!

this new key has been created that only contains the first 2 quarters! so no splicing needed :) `formattedEntityData.quarterProjections`

2024-02-12 15:38 UTC, keeysnc submitted a review, later dismissed

2024-02-12 15:54 UTC, ntsummers1 requested changes
Should this work be done in the EntityCardBottomSection instead? Would prevent a duplication of a little bit of code, but I might be missing something!

2024-02-12 20:10 UTC, cassandradanger commented
> Should this work be done in the EntityCardBottomSection instead? Would prevent a duplication of a little bit of code, but I might be missing something!

Hi Nick! great question - I placed the quantitative grid in this component because the "Projected quarterly expenditures" grid work was also done in this component, so I figured those would go together. 
Should we move both of those items to the EntityCardBottomSection? Or just the quantitative grid? I'm up for whatever, I was just following the previous pattern

2024-02-13 16:17 UTC, ntsummers1 approved these changes

2024-02-14 18:27 UTC, ailZhou approved these changes
lgtm! tested locally and the quarters in quantitative was there before filling it out and went away (as it should) when you filled out the card.

2024-02-14 20:36 UTC, merged