CMDCT-3444: [SAR] RE&T Field Validation
Enterprise-CMCS/macpro-mdct-mfp pull request #548
Opened 2024-04-19 13:20 UTC by karla-vm

### Description

Currently, the number fields in the SAR RE&T sections allow for any numbers, including decimals and negatives. As these represent people, they should _maaaaaybe_ not be negatives and decimals 😅

### Related ticket(s)

CMDCT-3444

---
### How to test

- Create and submit a WP as a state user (make sure to have applicable target populations, otherwise you won't be able to test the validation in the SAR)
- Approve that WP as an admin
- Create a SAR as a state user
- Navigate to the RE&T sections

You should get a validation error if you input a number less than one (1) or any decimals.

### Notes

N/A

---
### Pre-review checklist

- [ ] I have added [thorough](https://shorturl.at/aejkF) tests, if necessary
- [ ] I have updated relevant documentation, if necessary
- [ ] I have performed a self-review of my code
- [ ] I have manually tested this PR in the deployed cloud environment

---
### Pre-merge checklist

#### Review
- [ ] Design: This work has been reviewed and approved by design, if necessary
- [ ] Product: This work has been reviewed and approved by product owner, if necessary

#### Security
_If either of the following are true, notify the team's ISSO (Information System Security Officer)._

- [ ] These changes are significant enough to require an update to the SIA.
- [ ] These changes are significant enough to require a penetration test.
---

_convert to a different template: [test → val](?expand=1&template=test-to-val-deployment.md)_ | _[val → prod](?expand=1&template=val-to-prod-deployment.md)_

2024-04-22 13:52 UTC, gmrabian commented
I created and approved a WP on `stateuser1@test.com` in the deployed env. Feel free to jump straight to the SAR while validating :) 
https://de2379hujocus.cloudfront.net/

2024-04-22 14:02 UTC, gmrabian requested changes
Hi! Still need to fulfill two of the AC here:
- On blur, the value should be rounded to 0 places as needed.
- Fields in this section should allow whole numbers or N/A only, no decimals.

When I tested the fields errored on `N/A` and did not round decimals for me (which is how I read the first item above)

![Screenshot 2024-04-22 at 10 00 38 AM](https://github.com/Enterprise-CMCS/macpro-mdct-mfp/assets/57802560/5424bda2-a9f5-42b7-a60f-8f49fc315fd1)

2024-04-22 18:50 UTC, karla-vm commented on services/ui-src/src/utils/validation/schemas.ts
> +export const numberNotLessThanOne = () =>
That is correct, I just pushed an update for that! thank you ✨

2024-04-23 14:54 UTC, gmrabian submitted a review, later dismissed
changes work as expected :)

2024-04-23 14:54 UTC, gmrabian commented on services/ui-src/src/verbiage/errors.ts
> +  INVALID_WHOLE_NUMBER: 'Response must be a valid whole number or "N/A"',
not used anywhere

2024-04-23 14:56 UTC, ntsummers1 reviewed
nit: I think it might be good to update the schemas.test.ts file with the new integer schema just to have our bases covered with it.

2024-04-23 15:11 UTC, karla-vm commented
> nit: I think it might be good to update the schemas.test.ts file with the new integer schema just to have our bases covered with it.

Just updated the `app-api` test suite!

2024-04-23 16:09 UTC, benmartin-coforma reviewed
I have two comments:
1. I believe this removes the last reference to `checkStandardIntegerInputAgainstRegexes` in checkInputValidity.ts; if we're not using that, let's delete it.
2. One of the checks in that function validated the position of any dollar signs; without that check we can send the API dollar signs willy-nilly. The only restriction is that the first character must be a digit (because that's enough for `parseFloat` to be happy).

<img width="795" alt="image" src="https://github.com/Enterprise-CMCS/macpro-mdct-mfp/assets/126210497/f0ba4c08-f502-426d-8ab5-2777138e4549">

2024-04-23 17:04 UTC, jessabean commented
Was about to approve this PR and then Ben commented about the dollar signs! Will 👀 after that fix. Let me know if you need any help!

2024-04-23 17:06 UTC, karla-vm commented
> I have two comments:
> 
> 1. I believe this removes the last reference to `checkStandardIntegerInputAgainstRegexes` in checkInputValidity.ts; if we're not using that, let's delete it.
> 2. One of the checks in that function validated the position of any dollar signs; without that check we can send the API dollar signs willy-nilly. The only restriction is that the first character must be a digit (because that's enough for `parseFloat` to be happy).
> 
> <img alt="image" width="795" src="https://private-user-images.githubusercontent.com/126210497/324910134-f0ba4c08-f502-426d-8ab5-2777138e4549.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4OTE5MjgsIm5iZiI6MTcxMzg5MTYyOCwicGF0aCI6Ii8xMjYyMTA0OTcvMzI0OTEwMTM0LWYwYmE0YzA4LWY1MDItNDI2ZC04YWI1LTI3NzcxMzhlNDU0OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyM1QxNzAwMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zM2RiYjRhZjBmYmJlNGE0NWNmYzRhNjUwMzk1OThkNzdhYjQwYzczMjAxMDJjNDFiOTU2YzI3YmI2MWY0N2Q5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FVCMvE0LfQf1ODexW8Mn_bucvl9gvz9bvk5lAClsIXY">

Great catch, I brought back that check as part of my latest commit.

2024-04-23 18:04 UTC, karla-vm commented
> Was about to approve this PR and then Ben commented about the dollar signs! Will 👀 after that fix. Let me know if you need any help!

it is ready for eyes 👀

2024-04-23 18:18 UTC, benmartin-coforma approved these changes
The code looks good!

2024-04-23 19:06 UTC, merged